# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 热点分析.py
# Created on: 2016-08-01 19:49:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 热点分析 <输入要素类> <输入字段> <输出图层文件> <输出要素类> <距离范围或距离阈值> 
# Description: 
# 此地理处理工具结合了“热点分析”和“Z 得分渲染”两个工具的功能。
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
输入要素类 = arcpy.GetParameterAsText(0)

输入字段 = arcpy.GetParameterAsText(1)

输出图层文件 = arcpy.GetParameterAsText(2)

输出要素类 = arcpy.GetParameterAsText(3)

距离范围或距离阈值 = arcpy.GetParameterAsText(4)

# Local variables:
Input_Feature_Class = ""
Input_Field = ""
Distance_Band_or_Threshold_Distance = ""
Output_Feature_Class = ""
Results_Field = "GiUnknown"
Output_Layer_File = ""

# Process: Hot Spot Analysis (Getis-Ord Gi*)
arcpy.HotSpots_stats(Input_Feature_Class, Input_Field, Output_Feature_Class, "FIXED_DISTANCE_BAND", "EUCLIDEAN_DISTANCE", "NONE", Distance_Band_or_Threshold_Distance, "", "", "NO_FDR")

# Process: ZScore Rendering
arcpy.ZRenderer_stats(Output_Feature_Class, Results_Field, Output_Layer_File)

